name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-testrunnersg-${{ github.run_id }}-${{ github.run_attempt }}
      - image:windows-3.0
    steps:
      - name: test
        run: Write-Host "OS:$([System.Environment]::OSVersion.Version)"
        shell: pwsh
       


